
##   R O L E S   ##############################################################################

roles:
  id:
    any:              "ANY"
    legacy:
      super-user:     "SUPER_USER_COVIDCERTIFICATE"
      creator:        "CERTIFICATE_CREATOR"
    user:
      api:            "API_GW_USER"
      web:            "WEB_UI_USER"
      revocator:      "WEB_UI_REVOCATOR"
    cert:
      bulk:           "BULK_CERT_MANAGER"
      vacc:           "VACC_CERT_CREATOR"
      tourist:        "VACC_CERT_TOURIST_CREATOR"
      test:           "TEST_CERT_CREATOR"
      antibody:       "TEST_CERT_ANTIBODY_CREATOR"
      recovery:       "RECOVERY_CERT_CREATOR"
      rat:            "RECOVERY_RAT_CERT_CREATOR"
      exception:      "EXCEPTION_CERT_CREATOR"
    report:
      detail:         "DETAIL_REPORT_USER"
      agg:            "AGG_REPORT_USER"
      stats:          "STATS_REPORT_USER"
  groups:
    cert-creators-plus:   # INCLUDES exceptional
      ${roles.id.cert.vacc},${roles.id.cert.tourist},${roles.id.cert.test},${roles.id.cert.antibody},${roles.id.cert.recovery},${roles.id.cert.rat},${roles.id.cert.exception}
    cert-creators:        # EXCLUDES exceptional
      ${roles.id.cert.vacc},${roles.id.cert.tourist},${roles.id.cert.test},${roles.id.cert.antibody},${roles.id.cert.recovery},${roles.id.cert.rat}

  mappings:
  -
    intern:   ${roles.id.legacy.super-user}
    eiam:     "9500.GGG-Covidcertificate.SuperUserCC"
    claim:    "SuperUserCC"
  -
    intern:   ${roles.id.legacy.creator}
    eiam:     "9500.GGG-Covidcertificate.CertificateCreator"
    claim:    "CertificateCreator"
  -
    intern:   ${roles.id.user.web}
    eiam:     "9500.GGG-Covidcertificate.Web-UI-User"
    claim:    "Web-UI-User"
  -
    intern:   ${roles.id.user.api}
    eiam:     "9500.GGG-Covidcertificate.API-GW-User"
    claim:    "API-GW-User"
  -
    intern:   ${roles.id.user.revocator}
    eiam:     "9500.GGG-Covidcertificate.Web-UI-Revocator"
    claim:    "Web-UI-Revocator"
  -
    intern:   ${roles.id.cert.bulk}
    eiam:     "9500.GGG-Covidcertificate.BulkCert-Manager"
    claim:    "BulkCert-Manager"
  -
    intern:   ${roles.id.cert.exception}
    eiam:     "9500.GGG-Covidcertificate.ExceptionCert-Creator"
    claim:    "ExceptionCert-Creator"
  -
    intern:   ${roles.id.cert.recovery}
    eiam:     "9500.GGG-Covidcertificate.Recovery-Cert-Creator"
    claim:    "Recovery-Cert-Creator"
  -
    intern:   ${roles.id.cert.test}
    eiam:     "9500.GGG.TestCert-Creator"
    claim:    "TestCert-Creator"
  -
    intern:   ${roles.id.cert.vacc}
    eiam:     "9500.GGG-Covidcertificate.VaccCert-Creator"
    claim:    "VaccCert-Creator"
  -
    intern:   ${roles.id.cert.antibody}
    eiam:     "9500.GGG.TestCert-Antibody-Creator"
    claim:    "TestCert-Antibody-Creator"
  -
    intern:   ${roles.id.cert.rat}
    eiam:     "9500.GGG.Recovery-Rat-Cert-Creator"
    claim:    "Recovery-Rat-Cert-Creator"
  -
    intern:   ${roles.id.cert.tourist}
    eiam:     "9500.GGG-Covidcertificate.VaccCert-Tourist-Creator"
    claim:    "VaccCert-Tourist-Creator"
  -
    intern:   ${roles.id.report.agg}
    eiam:     "9500.GGG-Covidcertificate.Agg_Report_user"
    claim:    "Agg_Report_user"
  -
    intern:   ${roles.id.report.stats}
    eiam:     "9500.GGG-Covidcertificate.Stats_Report_user"
    claim:    "Stats_Report_user"
  -
    intern:   ${roles.id.report.detail}
    eiam:     "9500.GGG-Covidcertificate.Detail_Report_user"
    claim:    "Detail_Report_user"


# 1st level:  SERVICE
#   2nd level:  FUNCTION
#     from:       activates the function's permission with this date/time
#     until:      deactivates the function's permission after this date/time
#     mandatory:  this permission is needed to access the function
#     one-of:     one of the listed permissions is needed to access the function

services:

  ##   W E B - U I   ##############################################################################

  web-ui:

    functions:

    # navigation
    -
      identifier:   "main"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      one-of:       ${roles.id.any}
    -
      identifier:   "certificate-generation"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      one-of:       ${roles.groups.cert-creators-plus}
    -
      identifier:   "certificate-revocation"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      one-of:       ${roles.id.user.revocator},${roles.groups.cert-creators}
    -
      identifier:   "one-time-password-generation"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.api}
    -
      identifier:   "bulk-operations"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.cert.bulk}
    -
      identifier:   "reporting-self-service"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      one-of:       ${roles.id.report.detail}, ${roles.id.report.agg}, ${roles.id.report.stats}

    # create/revoke certificates
    -
      identifier:   "create-vaccine-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.vacc}
    -
      identifier:   "create-vaccine-tourist-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.tourist}
    -
      identifier:   "create-test-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.test}
    -
      identifier:   "create-antibody-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.antibody}
    -
      identifier:   "create-recovery-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.recovery}
    -
      identifier:   "create-recovery-rat-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.rat}
    -
      identifier:   "create-exceptional-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.exception}
    -
      identifier:   "revoke-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.revocator}
      one-of:       ${roles.groups.cert-creators-plus}

    # one-time-password
    -
      identifier:   "create-otp"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.api}

    # bulk operations
    -
      identifier:   "bulk-create-certificates"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.cert.bulk}
    -
      identifier:   "bulk-revoke-certificates"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.cert.bulk}

    # reports
    -
      identifier:   "report-a2"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.report.detail}
    -
      identifier:   "report-a3"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.report.agg}
    -
      identifier:   "report-a4"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.report.detail}
    -
      identifier:   "report-a5"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.report.agg}
    -
      identifier:   "report-a6"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.report.detail}
    -
      identifier:   "report-a7"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.report.agg}
    -
      identifier:   "report-a8"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.report.stats}
    -
      identifier:   "report-a9"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.report.stats}
    -
      identifier:   "report-a10"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.report.agg}

  ##   A P I - G A T E W A Y   ##############################################################################

  api-gateway:

    functions:

    # create/revoke certificates
    -
      identifier:   "create-vaccine-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.vacc}
    -
      identifier:   "create-vaccine-tourist-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.tourist}
    -
      identifier:   "create-test-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.test}
    -
      identifier:   "create-antibody-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.antibody}
    -
      identifier:   "create-recovery-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.recovery}
    -
      identifier:   "create-recovery-rat-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.rat}
    -
      identifier:   "create-exceptional-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.exception}
    -
      identifier:   "revoke-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.revocator}
      one-of:       ${roles.groups.cert-creators}

  ##   M A N A G E M E N T   ##############################################################################

  management:

    functions:

    # create/revoke certificates
    -
      identifier:   "create-vaccine-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.vacc}
      uri:          "/api/v1/covidcertificate/vaccination"
    -
      identifier:   "create-vaccine-tourist-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.tourist}
      uri:          "/api/v1/covidcertificate/vaccination-tourist"
    -
      identifier:   "create-test-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.test}
      uri:          "/api/v1/covidcertificate/test"
    -
      identifier:   "create-antibody-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.antibody}
      uri:          "/api/v1/covidcertificate/antibody"
    -
      identifier:   "create-recovery-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.recovery}
      uri:          "/api/v1/covidcertificate/recovery"
    -
      identifier:   "create-recovery-rat-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.rat}
      uri:          "/api/v1/covidcertificate/recovery-rat"
    -
      identifier:   "create-exceptional-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.web}
      one-of:       ${roles.id.cert.exception}
      uri:          "/api/v1/covidcertificate/exceptional"
    -
      identifier:   "revoke-certificate"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.revocator}
      one-of:       ${roles.groups.cert-creators-plus}
      uri:          "/api/v1/covidcertificate/revoke"

    # one-time-password
    -
      identifier:   "create-otp"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.user.api}
      uri:          "/api/v1/otp"

    # bulk operations
    -
      identifier:   "bulk-create-certificates"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.cert.bulk}
      uri:          "/api/v1/covidcertificate/csv"
    -
      identifier:   "bulk-revoke-certificates"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.cert.bulk}
#      TODO:
#      uri:          "/api/v1/covidcertificate/TODO"

    # valuesets
    -
      identifier:   "valuesets"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      one-of:       ${roles.id.user.api}, ${roles.id.user.web}
      uri:          "/api/v1/valuesets"
    -
      identifier:   "rapid-test-valueset"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      one-of:       ${roles.id.user.api}, ${roles.id.user.web}
      uri:          "/api/v1/valuesets/rapid-tests"
    -
      identifier:   "issuable-rapid-test-valueset"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      one-of:       ${roles.id.user.api}, ${roles.id.user.web}
      uri:          "/api/v1/valuesets/issuable-rapid-tests"
    -
      identifier:   "vaccines-valueset"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      one-of:       ${roles.id.user.api}, ${roles.id.user.web}
      uri:          "/api/v1/valuesets/vaccines"
    -
      identifier:   "issuable-vaccines-valueset"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      one-of:       ${roles.id.user.api}, ${roles.id.user.web}
      uri:          "/api/v1/valuesets/issuable-vaccines"
    -
      identifier:   "issuable-vaccines-valueset-by-system-source"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      one-of:       ${roles.id.user.api}, ${roles.id.user.web}
      uri:          "/api/v1/valuesets/issuable-vaccines/(\\w|-)+"
    -
      identifier:   "countries-valueset"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      one-of:       ${roles.id.user.api}, ${roles.id.user.web}
      uri:          "/api/v1/valuesets/countries"
    -
      identifier:   "countries-valueset-by-language"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      one-of:       ${roles.id.user.api}, ${roles.id.user.web}
      uri:          "/api/v1/valuesets/countries/(\\w|-)+"

    # extras
    -
      identifier:   "clear-caches"
      from:         2022-01-01T00:00:00
      until:        2099-12-31T23:59:59
      mandatory:    ${roles.id.legacy.super-user}
      uri:          "/api/v1/caches/clear"

  ##   R E P O R T   ##############################################################################

  report:

    functions:

    # reports
    -
      identifier: "report-a2"
      from: 2022-01-01T00:00:00
      until: 2099-12-31T23:59:59
      mandatory: ${roles.id.report.detail}
    -
      identifier: "report-a3"
      from: 2022-01-01T00:00:00
      until: 2099-12-31T23:59:59
      mandatory: ${roles.id.report.agg}
    -
      identifier: "report-a4"
      from: 2022-01-01T00:00:00
      until: 2099-12-31T23:59:59
      mandatory: ${roles.id.report.detail}
    -
      identifier: "report-a5"
      from: 2022-01-01T00:00:00
      until: 2099-12-31T23:59:59
      mandatory: ${roles.id.report.agg}
    -
      identifier: "report-a6"
      from: 2022-01-01T00:00:00
      until: 2099-12-31T23:59:59
      mandatory: ${roles.id.report.detail}
    -
      identifier: "report-a7"
      from: 2022-01-01T00:00:00
      until: 2099-12-31T23:59:59
      mandatory: ${roles.id.report.agg}
    -
      identifier: "report-a8"
      from: 2022-01-01T00:00:00
      until: 2099-12-31T23:59:59
      mandatory: ${roles.id.report.stats}
    -
      identifier: "report-a9"
      from: 2022-01-01T00:00:00
      until: 2099-12-31T23:59:59
      mandatory: ${roles.id.report.stats}
    -
      identifier: "report-a10"
      from: 2022-01-01T00:00:00
      until: 2099-12-31T23:59:59
      mandatory: ${roles.id.report.agg}
