info:
    build:
        artifact: '@project.artifactId@'
        description: '@project.description@'
        name: '@project.name@'
        version: '@project.version@'
logging:
  level:
    ch:
      admin:
        bit:
          jeap: DEBUG
        bag: DEBUG
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR
    org:
      hibernate: ERROR
      springframework:
        security:
          authentication:
            event:
              LoggerListener: ERROR
          oauth2:
            server:
              resource:
                web:
                  BearerTokenAuthenticationFilter: INFO
        web:
          servlet:
            resource:
              ResourceHttpRequestHandler: INFO
          filter:
            CommonsRequestLoggingFilter: INFO
    springfox:
      documentation:
        spring:
          web:
            readers:
              operation:
                CachingOperationNameGenerator: ERROR
  pattern:
    level: '[%X{correlationId}] %5p'
  config: classpath:logback-spring.xml
  file:
    name: log.log
server:
    port: 8120
    servlet:
        context-path: /
spring:
    application:
        name: cc-management-service
    datasource:
        url: jdbc:postgresql://localhost:3120/cc-management
        # Only for local development
        username: cc-management
        password: secret
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            pool-name: hikari-cp-${spring.application.name}
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show-sql: false
        open-in-view: false
    flyway:
        enabled: true
        clean-on-validation-error: false
        locations: classpath:db/migration/common, classpath:db/migration/postgresql
    jackson:
      serialization:
        write_dates_as_timestamps: false
    messages:
        basename: mail-messages,validation-messages
        encoding: UTF-8
        fallback-to-system-locale: false

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    session:
        store-type: none
    data:
        rest:
            base-path: /api
            max-page-size: 100
            default-page-size: 20
    main:
        banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: 'info,health,prometheus,loggers'
  endpoint:
    health:
      show-details: always
    flyway:
      enabled: true

cc-management-service:
  rest:
    connectTimeoutSeconds: 8
    readTimeoutSeconds: 8
  monitor:
    prometheus:
      secure: false
  rapid-test-import:
    cron: "0 0 03 * * *" ## At 03:00 AM
  pdf:
    show-watermark: true
  feature-toggle:
    features:
      #AppController
      - uri: ping
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      #CachesController
      - uri: caches/clear
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      #CovidCertificateGenerationController
      - uri: covidcertificate/vaccination
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: covidcertificate/vaccination-tourist
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: covidcertificate/test
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: covidcertificate/recovery
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: covidcertificate/recovery-rat
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: covidcertificate/antibody
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: covidcertificate/exceptional
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: covidcertificate/fromexisting/vaccination
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: covidcertificate/fromexisting/vaccination-tourist
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: covidcertificate/fromexisting/test
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: covidcertificate/fromexisting/recovery
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: covidcertificate/fromexisting/recovery-rat
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: covidcertificate/fromexisting/antibody
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: covidcertificate/fromexisting/exceptional
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      #CsvController
      - uri: covidcertificate/csv
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      #FeatureToggleController
      - uri: feature-toggle/features
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      #OneTimePasswordController
      - uri: otp
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      #RevocationController
      - uri: revocation
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      #RevocationListController
      - uri: revocation-list
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z


      #ValueSetsController
      - uri: valuesets
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: valuesets/rapid-tests
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: valuesets/issuable-rapid-tests
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: valuesets/vaccines
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: valuesets/issuable-vaccines
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: valuesets/issuable-vaccines/(\w|-)+
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: valuesets/countries
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

      - uri: valuesets/countries/(\w|-)+
        start: 2020-01-01T00:00:00.000Z
        end: 2099-12-31T23:59:59.999Z

cc-printing-service:
  billing:
    since-vaccination-date: 2021-07-15


