info:
  build:
    artifact: '@project.artifactId@'
    description: '@project.description@'
    name: '@project.name@'
    version: '@project.version@'
logging:
  level:
    ch:
      admin:
        bit:
          jeap: DEBUG
        bag: DEBUG
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR
    org:
      hibernate: ERROR
      springframework:
        security:
          authentication:
            event:
              LoggerListener: ERROR
          oauth2:
            server:
              resource:
                web:
                  BearerTokenAuthenticationFilter: INFO
        web: DEBUG
    springfox:
      documentation:
        spring:
          web:
            readers:
              operation:
                CachingOperationNameGenerator: ERROR
  pattern:
    level: '[%X{correlationId}] %5p'
  config: classpath:logback-spring.xml
  file:
    name: log.log
server:
  port: 8120
  servlet:
    context-path: /
spring:
  config:
    import: application-authorization.yml
  application:
    name: cc-management-service
  datasource:
    url: jdbc:postgresql://localhost:3120/cc-management
    # Only for local development
    username: cc-management
    password: secret
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: hikari-cp-${spring.application.name}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    clean-on-validation-error: false
    baseline-on-migrate: true
    table: flyway_schema_history
    baseline-version: 0
    locations: classpath:db/migration/common, classpath:db/migration/postgresql
  jackson:
    serialization:
      write_dates_as_timestamps: false
  messages:
    basename: mail-messages,validation-messages
    encoding: UTF-8
    fallback-to-system-locale: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  session:
    store-type: none
  data:
    rest:
      base-path: /api
      max-page-size: 100
      default-page-size: 20
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: 'info,health,prometheus,loggers'
  endpoint:
    health:
      show-details: always
    flyway:
      enabled: true

cc-management-service:
  auth:
    allow-unauthenticated: cc-api-gateway-service
  rest:
    connectTimeoutSeconds: 8
    readTimeoutSeconds: 8
  monitor:
    prometheus:
      secure: false
  rapid-test-import:
    cron: "0 0 03 * * *" ## At 03:00 AM
  update-deleted-marker:
    cron: "0 0 03 * * *" ## At 03:00 AM
    batch-size: 10000
    days-protected: 30
  vaccine-value-set-import:
    cron: "0 0 02 * * *" ## At 02:00 AM
    vaccine-base-url: "https://raw.githubusercontent.com/ehn-dcc-development/eu-dcc-valuesets/<version>/vaccine-medicinal-product.json"
    auth-holder-base-url: "https://raw.githubusercontent.com/ehn-dcc-development/eu-dcc-valuesets/<version>/vaccine-mah-manf.json"
    prophylaxis-base-url: "https://raw.githubusercontent.com/ehn-dcc-development/eu-dcc-valuesets/vaccine-prophylaxis.json"
  pdf:
    show-watermark: true
  feature-toggle:
    features:
      - type: vaccination-tourist
        uris:
          - covidcertificate/vaccination-tourist
        start: 2020-01-01T00:00:00.000Z
        end: 2022-02-16T00:00:00.000Z

      - type: antibody
        uris:
          - covidcertificate/antibody
        start: 2020-01-01T00:00:00.000Z
        end: 2022-02-16T00:00:00.000Z

      - type: exceptional
        uris:
          - covidcertificate/exceptional
        start: 2020-01-01T00:00:00.000Z
        end: 2022-02-16T00:00:00.000Z


cc-printing-service:
  billing:
    since-vaccination-date: 2021-07-15


